language: r

## GITHUB_PAT environment variable
## to allow uploading compiled Pages
## and installing private github packages
##
## Generate by:
## 1) install rubygems in Cygwin
## 2) gem install travis
## 3) ~/bin/travis login --pro
## 4) ~/bin/travis encrypt --pro -r tdmore-dev/tdmore GITHUB_PAT="my_secret_key"
env:
  global:
    - secure: "eRdUKzGRgegCU6BF+jQj8oh7ouEaQqR66hHqFd25Pe1hXrlERypDIJ+reDO2/nui0TmBapmEo6Z7TDAz9QwL7IK+jVjnY6LdQYrLOP5OYyEPj8TSJgpLxLOGV5Jf48h0YCv2a2WO42tu46TFfHuatr9ZLSioTP7wAfRu3c78kT4iolpYkcyGy7Y6cnTIWXzqjPDp1ypaBgRSpai+pXxTfvo4uQU8x5t3OiK7ELqFPAiBB0htJQuHT4hA8ipnw8dkhvmwd2l3sw8EhU4VHc44Q/YMoMxczKJrk7RBaVMwWT/SrK1Er/jWOhIZXcp5lMBGMT3ovKn7VygetCGt1zceooU7lnDSz9KW6IEhzTGqSsni/UkRpKrXjZY/favK/w+v5a0Y3d0d2/Jt6YyIolskxSotlSD8j9OoWkLI1wCle+Qk6ZIDXdRAZ/6h8yq75oUJFtKwd56U/JDrNVQ/6rlKFyELP3qLEcZnPh3VLAepx8QTGr1ULNzQteOa+urNTlUZ5X72W2Cf5gsePCsTcktiK8pqvt8PjQvDME3VF21ngDlGkwMNwfNhm0roDlckh2KajExc3Yxx801dvYTVETNuyG0DyvapyeaDSUf8hyTiH3z3mOBjbaUtCJkJTNSj3EVf0LUxq598npREOQwYaxiy0M9ypu8FTDnh1zFRqFSXcS0="

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library
  packages: true

# apt_packages is an travis-r-specific key, applied in the *script* section
# we override the *script* section
# instead, we need to use the 'apt' addon
addons:
  apt:
    packages:
      - libudunits2-dev
      - lbzip2
      - libharfbuzz-dev
      - libfribidi-dev
      - libmpfr-dev
      - libgit2-dev
      - libdparser-dev


install:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  # use renv purely to restore the packages from renv.lock
  - Rscript -e "renv::restore(library=.libPaths()[1])"
  # Install PhantomJS (if not cached)
  - Rscript -e 'shinytest::installDependencies()'
  - Rscript -e "devtools::install_github('tdmore-dev/tdmore@"$TRAVIS_BRANCH"', dependencies=FALSE)"

script:
  - Rscript -e 'devtools::check()'

stages:
  - name: after_success
    if: branch = master

after_success:
  - Rscript -e 'library(covr);codecov(quiet=FALSE, token=Sys.getenv("CODECOV_TOKEN"))'
  - Rscript -e 'library(pkgdown);pkgdown::build_site()'

deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep_history: true
  on:
    branch: master

notifications:
  email:
    recipients:
      - ruben.faelens@kuleuven.be
      - nicolas.luyckx@sgs.com
    on_success: change # default: change
    on_failure: always # default: always
